complete_from_path = "true"
ctrlc_exit = false
disable_table_indexes = false
nonzero_exit_errors = false
path = []
pivot_mode = "auto"
prompt = "starship prompt"
skip_welcome_message = true
startup = [
    "source ~/.zoxide.nu",
    "alias g = git",
    "alias t = tig",
    "alias h = htop",
    "alias v = nvim",
]
table_mode = "light"

[env]
DIFF_AGAINST = "upstream/main"
EDITOR = "vim"
PYENV_SHELL = "nu"
http_proxy = "http://localhost:8888"
https_proxy = "http://localhost:8888"
no_proxy = "localhost,127.0.0.1,0.0.0.0"

[line_editor]
auto_add_history = true
bell_style = "none"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "vi"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = false
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 2
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
